Update 04-chapter-3-adding-mutations-to-your-api.mdx
graphql-nexus/nexus pull request #757
Opened 2020-12-26 05:12 UTC by canrozanes

This is something I came across as I was going through the tutorial. Not explicitly setting an export key on contextType appears to throw a Typescript error:

`Property 'export' is missing in type '{ module: string; alias: string; }' but required in type 'TypingImport'.`

2020-12-30 15:05 UTC, namoscato reviewed
Thanks, @canrozanes!

I noticed this as well and was going to make this change, which removes the optional `alias` in favor of `export`. It might be a simpler option, unless we find it useful to introduce `alias` in the tutorial?

2020-12-30 15:05 UTC, namoscato commented on docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
> ++    export: "Context"                               // 4
```suggestion
+    export: "Context",                              // 3
```

2020-12-30 15:05 UTC, namoscato commented on docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
> +    export: "Context"                               // 4
```suggestion
    export: "Context",                              // 3
```

2020-12-30 15:05 UTC, namoscato commented on docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
> +1. Name of the type generated in nexus-typegen
```suggestion
```

2021-01-04 01:28 UTC, jasonkuhrt requested changes
This may have already been fixed. Please rebase and see.

2021-02-06 22:31 UTC, closed without merging